# ==========================================
# Application Configuration
# ==========================================
spring.application.name=portfolio-contact-service

# ==========================================
# Server
# ==========================================
server.port=8080

# ==========================================
# Resend Configuration
# ==========================================
resend.api.key=${RESEND_API_KEY}

# ==========================================
# Receiver Email
# ==========================================
portfolio.mail.to=${MAIL_TO}

# ==========================================
# Logging
# ==========================================
logging.level.root=INFO